name: boletim_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - numpy
  - requests
  - gdal=3.6.2
  - python-dotenv
  - psycopg2
  - streamlit
  - geopandas=1.0.1
  - plotly
  - rasterio=1.4.3
  - shapely
  - fiona=1.10.1
  - leafmap
  - matplotlib
  - schedule
  - pip
  - pip:
      - webdriver-manager
      - selenium
      - fpdf
      - html2image
  
  